development:
  adapter: postgresql
  encoding: unicode
  database: dashboard_development
  pool: 5
  username: <%= `whoami` %>
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: dashboard_test
  pool: 5
  username: <%= `whoami` %>
  password:
  min_messages: WARNING
